### ISSUE TITLE
ModuleNotFoundError: No module named 'exceptions'

### ISSUE THREAD

**Issue by Kokozzi** [sendsay-ru/sendsay-api-python#1]
Full lib seems to be broken because of incorrect modules imports:

```
>>> from sendsay.api import SendsayAPI                                                                                 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../.venv/lib/python3.7/site-packages/sendsay/api.py", line 8, in <module>
    from exceptions import SendsayAPIError
ModuleNotFoundError: No module named 'exceptions'
```

Tested with Python 3.7.5, Ubuntu 18.04.3 LTS.

**Comment by hezymal** [comment]
Same problem:
```
Traceback (most recent call last):
  File ".\index.py", line 2, in <module>
    from sendsay.api import SendsayAPI
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sendsay\api.py", line 8, in <module>
    from exceptions import SendsayAPIError
ModuleNotFoundError: No module named 'exceptions'
```

**Comment by hezymal** [comment]
Traceback (most recent call last):
  File ".\index.py", line 2, in <module>
    from sendsay.api import SendsayAPI
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\sendsay\api.py", line 8, in <module>
    from exceptions import SendsayAPIError
ModuleNotFoundError: No module named 'exceptions'

**Comment by Kokozzi** [comment]
After direct message to SendSay support they mentioned, that it's only python2 lib. It won't work with python3.

**Comment by hezymal** [comment]
Enough to fix the import of exceptions in `api.py` to work on python3:
```python
from .exceptions import SendsayAPIError // add dot "." before "exceptions"
```

**Comment by feikeker** [comment]
same issue
`Traceback (most recent call last):
  File "E:\02 Python 基础\练习代码\word.py", line 2, in <module>
    from docx import Document
  File "C:\Users\admin\anaconda3\lib\site-packages\docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'`

**Comment by Vaishalinicky** [comment]
root@aeb4686b140b:/tmp# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cql/__init__.py", line 17, in <module>
    from cql.apivalues import *
  File "/usr/local/lib/python3.8/dist-packages/cql/apivalues.py", line 17, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
>>>

same issue even i have

**Comment by Luferov** [comment]
oh god this is sad
